export const mock = {
  catId: 0,
  hasPrivilege: false,
  level: 1,
  subCategoryTreeItemList: [
    {
      catId: 1,
      hasPrivilege: false,
      itemName: "农业",
      level: 2,
      subCategoryTreeItemList: [
        {
          catId: 100004477,
          hasPrivilege: false,
          itemName: "农用设备",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 145,
              hasPrivilege: false,
              itemName: "农用温室",
              level: 4,
            },
            {
              catId: 130,
              hasPrivilege: false,
              itemName: "水产养殖设备",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 13002,
                  hasPrivilege: false,
                  itemName: "养殖笼兜",
                  level: 5,
                },
                {
                  catId: 13099,
                  hasPrivilege: false,
                  itemName: "其他水产业设备",
                  level: 5,
                },
              ],
            },
          ],
        },
        {
          catId: 138,
          hasPrivilege: false,
          itemName: "农业废弃物",
          level: 3,
        },
        {
          catId: 100002818,
          hasPrivilege: false,
          itemName: "动物饲料",
          level: 3,
        },
      ],
    },
    {
      catId: 3,
      hasPrivilege: false,
      itemName: "服装",
      level: 2,
      subCategoryTreeItemList: [
        {
          catId: 201607003,
          hasPrivilege: false,
          itemName: "婴儿服装",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 201622703,
              hasPrivilege: false,
              itemName: "婴儿围嘴",
              level: 4,
            },
            {
              catId: 201614402,
              hasPrivilege: false,
              itemName: "婴儿套装",
              level: 4,
            },
            {
              catId: 201622402,
              hasPrivilege: false,
              itemName: "婴儿连衣裙",
              level: 4,
            },
            {
              catId: 201625201,
              hasPrivilege: false,
              itemName: "婴儿卫衣帽衫",
              level: 4,
            },
            {
              catId: 201617103,
              hasPrivilege: false,
              itemName: "婴儿夹克&外套",
              level: 4,
            },
            {
              catId: 201622102,
              hasPrivilege: false,
              itemName: "婴儿裤子",
              level: 4,
            },
            {
              catId: 201617104,
              hasPrivilege: false,
              itemName: "婴儿爬爬服",
              level: 4,
            },
            {
              catId: 201623102,
              hasPrivilege: false,
              itemName: "婴儿衬衣上衣",
              level: 4,
            },
            {
              catId: 201615103,
              hasPrivilege: false,
              itemName: "婴儿短裙",
              level: 4,
            },
            {
              catId: 201625301,
              hasPrivilege: false,
              itemName: "婴儿睡袋",
              level: 4,
            },
            {
              catId: 201616903,
              hasPrivilege: false,
              itemName: "婴儿毛衣",
              level: 4,
            },
            {
              catId: 201774103,
              hasPrivilege: false,
              itemName: "婴儿泳衣",
              level: 4,
            },
            {
              catId: 201620003,
              hasPrivilege: false,
              itemName: "婴儿T恤",
              level: 4,
            },
            {
              catId: 201620203,
              hasPrivilege: false,
              itemName: "婴儿睡衣",
              level: 4,
            },
            {
              catId: 201625401,
              hasPrivilege: false,
              itemName: "婴儿背心",
              level: 4,
            },
            {
              catId: 201769204,
              hasPrivilege: false,
              itemName: "其他婴儿服装",
              level: 4,
            },
          ],
        },
        {
          catId: 127660035,
          hasPrivilege: false,
          itemName: "儿童服装",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 201610402,
              hasPrivilege: false,
              itemName: "男童服装",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 201606802,
                  hasPrivilege: false,
                  itemName: "男童套装",
                  level: 5,
                },
                {
                  catId: 201598003,
                  hasPrivilege: false,
                  itemName: "男童大衣外套",
                  level: 5,
                },
                {
                  catId: 201598703,
                  hasPrivilege: false,
                  itemName: "男童卫衣帽衫",
                  level: 5,
                },
                {
                  catId: 201612001,
                  hasPrivilege: false,
                  itemName: "男童夹克",
                  level: 5,
                },
                {
                  catId: 201610403,
                  hasPrivilege: false,
                  itemName: "男童牛仔服",
                  level: 5,
                },
                {
                  catId: 201598304,
                  hasPrivilege: false,
                  itemName: "男童裤子",
                  level: 5,
                },
                {
                  catId: 201611901,
                  hasPrivilege: false,
                  itemName: "男童衬衣",
                  level: 5,
                },
                {
                  catId: 201600105,
                  hasPrivilege: false,
                  itemName: "男童短裤",
                  level: 5,
                },
                {
                  catId: 201607403,
                  hasPrivilege: false,
                  itemName: "男童睡衣",
                  level: 5,
                },
                {
                  catId: 201601505,
                  hasPrivilege: false,
                  itemName: "男童运动装",
                  level: 5,
                },
                {
                  catId: 201600203,
                  hasPrivilege: false,
                  itemName: "男童西服套装",
                  level: 5,
                },
                {
                  catId: 201607902,
                  hasPrivilege: false,
                  itemName: "男童毛衣",
                  level: 5,
                },
                {
                  catId: 201611402,
                  hasPrivilege: false,
                  itemName: "男童泳衣",
                  level: 5,
                },
                {
                  catId: 201609304,
                  hasPrivilege: false,
                  itemName: "男童T恤&Polo衫",
                  level: 5,
                },
                {
                  catId: 201603806,
                  hasPrivilege: false,
                  itemName: "男童背心",
                  level: 5,
                },
                {
                  catId: 201602405,
                  hasPrivilege: false,
                  itemName: "男童内衣",
                  level: 5,
                },
                {
                  catId: 201602604,
                  hasPrivilege: false,
                  itemName: "男童马甲",
                  level: 5,
                },
                {
                  catId: 201605003,
                  hasPrivilege: false,
                  itemName: "其他男童装",
                  level: 5,
                },
              ],
            },
            {
              catId: 127676026,
              hasPrivilege: false,
              itemName: "亲子装",
              level: 4,
            },
            {
              catId: 201610903,
              hasPrivilege: false,
              itemName: "女童服装",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 201596706,
                  hasPrivilege: false,
                  itemName: "女童衬衫",
                  level: 5,
                },
                {
                  catId: 201607005,
                  hasPrivilege: false,
                  itemName: "女童套装",
                  level: 5,
                },
                {
                  catId: 201607004,
                  hasPrivilege: false,
                  itemName: "女童大衣外套",
                  level: 5,
                },
                {
                  catId: 201608504,
                  hasPrivilege: false,
                  itemName: "女童连衣裙",
                  level: 5,
                },
                {
                  catId: 201606505,
                  hasPrivilege: false,
                  itemName: "女童卫衣帽衫",
                  level: 5,
                },
                {
                  catId: 201602605,
                  hasPrivilege: false,
                  itemName: "女童夹克",
                  level: 5,
                },
                {
                  catId: 201596802,
                  hasPrivilege: false,
                  itemName: "女童牛仔服",
                  level: 5,
                },
                {
                  catId: 201610503,
                  hasPrivilege: false,
                  itemName: "女童连身衣",
                  level: 5,
                },
                {
                  catId: 201603703,
                  hasPrivilege: false,
                  itemName: "女童长裤",
                  level: 5,
                },
                {
                  catId: 201598902,
                  hasPrivilege: false,
                  itemName: "女童短裤",
                  level: 5,
                },
                {
                  catId: 201597305,
                  hasPrivilege: false,
                  itemName: "女童短裙",
                  level: 5,
                },
                {
                  catId: 201598605,
                  hasPrivilege: false,
                  itemName: "女童睡衣",
                  level: 5,
                },
                {
                  catId: 201600905,
                  hasPrivilege: false,
                  itemName: "女童运动装",
                  level: 5,
                },
                {
                  catId: 201607804,
                  hasPrivilege: false,
                  itemName: "女童毛衣",
                  level: 5,
                },
                {
                  catId: 201599903,
                  hasPrivilege: false,
                  itemName: "女童泳衣",
                  level: 5,
                },
                {
                  catId: 201611302,
                  hasPrivilege: false,
                  itemName: "女童T恤&polo 衫",
                  level: 5,
                },
                {
                  catId: 201601602,
                  hasPrivilege: false,
                  itemName: "女童内衣",
                  level: 5,
                },
                {
                  catId: 201599405,
                  hasPrivilege: false,
                  itemName: "女童马甲",
                  level: 5,
                },
                {
                  catId: 201602606,
                  hasPrivilege: false,
                  itemName: "女童其他服装",
                  level: 5,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

const mocks = {
  catId: 0,
  hasPrivilege: false,
  level: 1,
  subCategoryTreeItemList: [
    {
      catId: 1,
      hasPrivilege: false,
      itemName: "农业",
      level: 2,
      subCategoryTreeItemList: [
        {
          catId: 100004477,
          hasPrivilege: false,
          itemName: "农用设备",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 130,
              hasPrivilege: false,
              itemName: "水产养殖设备",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 13002,
                  hasPrivilege: false,
                  itemName: "养殖笼兜",
                  level: 5,
                },
              ],
            },
          ],
        },
        {
          catId: 138,
          hasPrivilege: false,
          itemName: "农业废弃物",
          level: 3,
        },
      ],
    },
    {
      catId: 3,
      hasPrivilege: false,
      itemName: "服装",
      level: 2,
      subCategoryTreeItemList: [
        {
          catId: 201607003,
          hasPrivilege: false,
          itemName: "婴儿服装",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 201622703,
              hasPrivilege: false,
              itemName: "婴儿围嘴",
              level: 4,
            },
            {
              catId: 201614402,
              hasPrivilege: false,
              itemName: "婴儿套装",
              level: 4,
            },
          ],
        },
        {
          catId: 127660035,
          hasPrivilege: false,
          itemName: "儿童服装",
          level: 3,
          subCategoryTreeItemList: [
            {
              catId: 201610402,
              hasPrivilege: false,
              itemName: "男童服装",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 201606802,
                  hasPrivilege: false,
                  itemName: "男童套装",
                  level: 5,
                },
                {
                  catId: 201598003,
                  hasPrivilege: false,
                  itemName: "男童大衣外套",
                  level: 5,
                },
                {
                  catId: 201598703,
                  hasPrivilege: false,
                  itemName: "男童卫衣帽衫",
                  level: 5,
                },
                {
                  catId: 201612001,
                  hasPrivilege: false,
                  itemName: "男童夹克",
                  level: 5,
                },
              ],
            },
            {
              catId: 127676026,
              hasPrivilege: false,
              itemName: "亲子装",
              level: 4,
            },
            {
              catId: 201610903,
              hasPrivilege: false,
              itemName: "女童服装",
              level: 4,
              subCategoryTreeItemList: [
                {
                  catId: 201596706,
                  hasPrivilege: false,
                  itemName: "女童衬衫",
                  level: 5,
                },
                {
                  catId: 201607005,
                  hasPrivilege: false,
                  itemName: "女童套装",
                  level: 5,
                },
                {
                  catId: 201607004,
                  hasPrivilege: false,
                  itemName: "女童大衣外套",
                  level: 5,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
